# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $cm := (index .Values "cert-manager") }}
{{- if $cm.selfSigned.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitpod-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: gitpod-ca
  secretName: gitpod-ca-certificate
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
{{- end }}