packages:
  - name: lib
    type: yarn
    srcs:
      - package.json
      - build.sh
    deps:
      - components/local-app-api:proto
      - components/supervisor-api/typescript-grpcweb:lib
    env:
      - PROTOLOC=components-local-app-api--proto
    config:
      packaging: library
      dontTest: true
      commands:
        build: ["yarn", "build"]
      yarnLock: ${coreYarnLockBase}/../yarn.lock
  - name: publish
    type: generic
    env:
      - DO_PUBLISH=${publishToNPM}
    argdeps:
      - npmPublishTrigger
    deps:
      - :lib
      - components/gitpod-protocol:scripts
      - components/supervisor-api/typescript-grpcweb:publish
    config:
      commands:
        - ["node", "components-gitpod-protocol--scripts/publish.js", "${version}", "components-local-app-api-typescript-grpcweb--lib/package"]
